language: node_js
node_js:
  - "v16.13.0"
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build
after_script: # Upload coverage reports
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
notifications:
  email:
    on_success: change
    on_failure: always
