// Type definitions for react-tunes-player
// Project: A simple .ogg/.mp3 player.
// Definitions by: Muzikayise Flynn Buthelezi (zuluCoda)
// Generated by: https://github.com/zulucoda/react-tunes-player-types

/// <reference types="react" />
declare type Tune = {
  tune: string;
  name: string;
  album: string;
};
declare type TunesProp = {
  tunes?: Tune[];
  oldPlayer?: boolean;
};
export declare const ReactTunesPlayer: {
  ({ tunes, oldPlayer }: TunesProp): JSX.Element;
  defaultProps: {
    tunes: never[];
    oldPlayer?: boolean;
  };
  propTypes: {
    tunes: import("prop-types").Validator<(Required<import("prop-types").InferProps<{
      tune: import("prop-types").Validator<string>;
      name: import("prop-types").Validator<string>;
      album: import("prop-types").Validator<string>;
    }>> | null | undefined)[]>;
    oldPlayer?: boolean;
  };
};
export default ReactTunesPlayer;


